### ISSUE TITLE
Download latest version of FFmpeg

### ISSUE THREAD

**Issue by MrTech12** [MrTech12/MediaManager#10]
# Reason
Currently, the application does not automatically download FFmpeg.
The user needs to put a copy in the same location as the executable.

## Details
The program needs to check if FFmpeg is already present in the same folder.
If it isn't present, the program will need to lookup the latest version and download it. The downloaded file will also need to be verified for authenticity.
One of the download locations, [gyan.dev](https://www.gyan.dev/ffmpeg/builds) offers SHA-256 hashes for the latest version.

## Todo

- [ ] Check for the presence of FFmpeg.
- [ ] Lookup the current version of FFmpeg.
- [ ] Download the current version of FFmpeg.
- [ ] Verify the downloaded file.

## Relevant links
[gyan.dev](https://www.gyan.dev/ffmpeg/builds)
